version: '3'

services:
  # First, build base image for shared dependencies
  base-image:
    build:
      context: .
      dockerfile: ./base/Containerfile
    image: custom-python-base

  fastapi:
    build:
      context: .
      dockerfile: ./fastapi/Containerfile
      args:
        BASE_IMAGE: custom-python-base
    depends_on:
      - base-image
    ports:
      - 8000:8000

  streamlit:
    build:
      context: .
      dockerfile: ./streamlit/Containerfile
      args:
        BASE_IMAGE: custom-python-base
    depends_on:
      - base-image
    ports:
      - 8501:8501

  flask:
    build:
      context: .
      dockerfile: ./flask/Containerfile
      args:
        BASE_IMAGE: custom-python-base
    depends_on:
      - base-image
    ports:
      - 5555:5555