# If passed a base image from a containerfile, it will use that
# to save on storage space. Otherwise, build from scratch.
ARG BASE_IMAGE=python:3.9-slim
FROM ${BASE_IMAGE}

WORKDIR /app

COPY streamlit/requirements.txt .
COPY ner.py .

RUN pip install -r requirements.txt

COPY streamlit/app_streamlit.py .

CMD ["streamlit", "run", "app_streamlit.py"]